"""add_document_embeddings_vector_table

Revision ID: a44d02a086d8
Revises: af4c4ec995eb
Create Date: 2026-09-14 01:45:47.393554

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a44d02a086d8"
down_revision: str | Sequence[str] | None = "2ea5ab9476fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
